travis:
  secure:
    BINSTAR_TOKEN: H+z/Vv0vJRzkiOU+3hNLkn1XPhbwvUHgmlvprH3CaiCgybIZzdI2ahxqjO/j6KgEE76j4UlYSc4rJIDCdIPfS6qtKiQ5JTM3Aupur5x5hNf6+6GfT4A+Gybhn2cczgnJoswWTxPbNwl6G5siahpO2wrUk5U/olMIPDGS+wd2UebULnynlKeIJBx7pbNkz5DoJIwnJJnxZ4NzJwx6VpKHLejEPdToBcedyz9SSYlO8ITIbQUj8fXM5GpNttQSURL++qjCkQsfALBgT81daLha/1RpanTenkOh/TbPawy8wyctUJjqUc/tFYENYYUOJ4H0iM4b2A5W/xEP9hDVHwn/ozK1vzRMEj/nytokUNxFIUktWtD0WlypLKU+VOoUuAhfmdmd/iQsVk+lTk7hP0NZ3Jn2t0zRzpgvY4VJ2266zUq1l8MtdVhw38vnbAmM7MfPu+R9BYlESy4g2zhjL0KKdgh/YtLZtzV8Gcx6GTI1dMIUCQJOQZ/XguBEQvES5nZlC6SI8/eSSif6w9Dk2jQtwzPtXJffz6LqHn+/DVs4Y9gbv0VYD62l/epX/cWSPXcdDxrmsc4/VXYL5461YnvqeajaYoT47NRroQdR3MCa0GQzJQoOTTjgrYxO8kZql0xgxP0wkaC44wnFqgaBHpxEjvAszSq5QOOSnwsfOCOhLZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
